version: '3'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      WAIT_HOST: mongo:27000 #might need adjustment
  mongo:
    image: mongo:4.2.5
    ports:
      - "27000:27000"
