version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      WAIT_HOST: mongo:27017
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
